version: '2'
services:
  jenkins:
    group_add:
    #docker
    - '999'
    image: jenkins/jenkins:lts
    stdin_open: true
    volumes:
    - /home/hanrenwei/Docker/var/jenkins_home:/var/jenkins_home
    - /home/hanrenwei/.m2:/var/jenkins_home/.m2
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/bin/docker:/usr/bin/docker
    - /usr/lib/x86_64-linux-gnu/libltdl.so.7:/usr/lib/x86_64-linux-gnu/libltdl.so.7
    - /usr/bin/rancher-compose:/usr/bin/rancher-compose
    - /etc/timezone:/etc/timezone
    tty: true
    ports:
    - 80:8080/tcp
    labels:
      io.rancher.container.pull_image: always
